name:  FunctionStack
author:  arieh
current:  1.3.2
category:  Utilities
tags:  [Class,demo-tools]
docs: http://moodocs.net/arieh/functionstack/FunctionStack  
demo: http://arieh.github.com/FunctionStack/
